# Generated by Django 5.0.6 on 2025-07-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveldb', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='link_url_name',
        ),
    ]
